CREATE TABLE tblStaff (
	StaffID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ManagerID INT,
	UserName VARCHAR(25) NOT NULL,
	Title VARCHAR(8) NOT NULL,
	FirstName VARCHAR(32) NOT NULL,
	LastName VARCHAR(32) NOT NULL,
	Password VARCHAR(MAX) NOT NULL,
	Role VARCHAR(32) NOT NULL,
	AddressLine1 VARCHAR(32),
	AddressLine2 VARCHAR(32),
	AddressLine3 VARCHAR(32),
	AddressLine4 VARCHAR(32),
	Postcode VARCHAR(8),
	ContactNo VARCHAR(16) NOT NULL,
	EmailAddress VARCHAR(320) NOT NULL,
	DateOfBirth DATE NOT NULL
);

CREATE TABLE tblCustomer (
	CustomerID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Title VARCHAR(8) NOT NULL,
	FirstName VARCHAR(32) NOT NULL,
	LastName VARCHAR(32) NOT NULL,
	AddressLine1 VARCHAR(32),
	AddressLine2 VARCHAR(32),
	AddressLine3 VARCHAR(32),
	AddressLine4 VARCHAR(32),
	Postcode VARCHAR(8),
	ContactNo VARCHAR(16) NOT NULL,
	EmailAddress VARCHAR(320),
	DateOfBirth DATE NOT NULL
);

CREATE TABLE tblRoom (
	RoomID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	RoomNo VARCHAR(32) NOT NULL,
	RoomType VARCHAR(16) NOT NULL,
	Disability BIT NOT NULL
);

CREATE TABLE tblBooking (
	BookingID INT PRIMARY KEY IDENTITY(1000000,1) NOT NULL,
	RoomID INT NOT NULL,
	CustomerID INT NOT NULL,
	StaffID INT NOT NULL,
	Breakfast BIT NOT NULL,
	NoOfAdult INT NOT NULL,
	NoOfChildren INT NOT NULL,
	CheckInDate DATETIME NOT NULL,
	CheckOutDate DATETIME NOT NULL
);

CREATE TABLE tblInvoice (
	InvoiceID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	BookingID INT NOT NULL,
	CustomerID INT NOT NULL,
	TotalCost MONEY NOT NULL
);
